services:
  web:
    build:
      context: .
      target: production
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_HTTP_CLIENT=${VITE_HTTP_CLIENT}
    container_name: epaa-web-prod
    restart: unless-stopped # mejor que always en algunos casos
    ports:
      - '80:80' # o "8080:80" si 80 está ocupado
    networks:
      - epaa-network
    healthcheck:
      test: ['CMD', 'wget', '-q', '--spider', 'http://127.0.0.1/health']
      interval: 30s
      timeout: 10s
      retries: 3
    read_only: true # buena práctica de seguridad
    tmpfs:
      - /var/cache/nginx
      - /var/run
      - /tmp

networks:
  epaa-network:
    driver: bridge
